[package]
name = "resume"
version = "0.1.0"
edition = "2024"

[dependencies]
html = "0.6.3"
linkedin-api = "0.1.0"
regex = "1.11.3"
serde = "1.0.227"
serde_json = "1.0.145"
svg = "0.18.0"
typst = "0.13.1"
url = "2.5.7"
validator = "0.20.0"
