[package]
name = "resume"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
html = "0.6.3"
linkedin-api = "0.5.0"
regex = "1.11.3"
serde = "1.0.227"
serde_json = "1.0.145"
svg = "0.18.0"
time = "0.3.44"
tokio = "1.47.1"
typst = "0.13.1"
url = "2.5.7"
validator = "0.20.0"
